debug = false
checkNewVersion = true
logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik"
watch = true
exposedbydefault = false
swarmmode = true

[acme]
email = ""
storage = "acme.json"
entryPoint = "https"
onDemand = true
OnHostRule = true
acmeLogging = true